version: '3.8'

services:
  # Service 1: The Database
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecom_db
    ports:
      - "5432:5432"

  # Service 2: Your FastAPI App
  web:
    build: .
    # This command makes the app wait for the DB to be ready, then runs the app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # This connects the app to the 'db' service above
      - DATABASE_URL=postgresql://postgres:password@db/ecom_db
    depends_on:
      - db

volumes:
  postgres_data: